name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py  
      - name: Get current date
        id: date
        run: |
          echo "time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Result reporting
        env:
          report_path: .github/reports
          report_md_path: .github/reports/${{ env.time }}.md
          feature_image: images/feature_importance-${{ env.time }}.png
          residuals_image: images/residuals-${{ env.time }}.png
            
        run: |
          echo ${{ env.time }}
          echo $report_path
          echo $report_path/$feature_image
          echo " # GITHUB ACTION SELF HOSTED" >> $report_md_path
          echo " ## Model Performance" >> $report_md_path
          cat metrics.txt >> $report_md_path
          cp feature_importance.png $report_path/$feature_image
          cp residuals.png $report_path/$residuals_image
          echo " ## Visulization" >> $report_md_path
          echo "![image]($feature_image)" >> $report_md_path
          echo "![image]($residuals_image)" >> $report_md_path
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated README
          file_pattern: '.github/reports/*'
          branch: experiment1
