name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py  
      - name: Get current date
        id: date
        run: |
          echo "time=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
        env:
          report_path: .github/reports/${{ env.date }}.md
          feature_image: .github/images/feature_importance-${{ env.date }}.png
          residuals_image: .github/images/residuals-${{ env.date }}.png
      - name: Result reporting
        run: |
          echo ${{ env.time }}
          echo ${{ env.report_path }}
          echo ${{ env.feature_image }}
          echo " ## Model Performance" >> report_path
          cat metrics.txt >> report_path
          cp feature_importance.png feature_image
          cp residuals.png residuals_image
          echo " ## Visulization" >> report_path
          echo "![image](.github/images/feature_importance.png)" >> report_path
          echo "![image](.github/images/residuals.png)" >> report_path
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated README
          file_pattern: 'report_path feature_image residuals_image'
          branch: experiment1
