name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "report=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.report }}" 
