name: cml-wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages      
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py  
      - name: Result reporting
        run: |
          echo " ## Model Performance" >> report.md
          cat metrics.txt >> report.md
          #cp feature_importance.png .github/images/feature_importance.png
          #cp residuals.png .github/images/residuals.png
          echo " ## Visulization" >> report.md
          #echo "![image](.github/images/feature_importance.png)" >> report.md
          #echo "![image](.github/images/residuals.png)" >> report.md          
          cml-publish feature_importance.png --md >>report.md
          cml-publish residuals.png --md >>report.md
          #echo "![](./feature_importance.png)" >> report.md
          cml-send-comment report.md

