name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py
          echo "Model Performance"
          cat metrics.txt
