name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py  
      - name: Result reporting
        run: |
          echo " ## Model Performance" >> report.md
          cat metrics.txt >> report.md
          echo " ## Visulization" >> report.md
          echo "![image](feature_importance.png)" >> report.md
          echo "![image](residuals.png)" >> report.md          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated README
          file_pattern: '*.md'
          branch: experiment1
