name: wine-model
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: |
          # Your ML workflow goes here
          python train.py  
      - name: Get current date
        id: date
        run: |
          echo "report=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Result reporting
        run: |
          echo ${{ env.report }}
          echo ${{ env.report }}.md
          echo .github/images/${{ env.report }}.md
          echo " ## Model Performance" >> .github/images/${{ env.report }}.md
          cat metrics.txt >> .github/images/${{ env.report }}.md
          cp feature_importance.png .github/images/feature_importance.png
          cp residuals.png .github/images/residuals.png
          echo " ## Visulization" >> .github/images/${{ env.report }}.md
          echo "![image](.github/images/feature_importance.png)" >> .github/images/${{ env.report }}.md
          echo "![image](.github/images/residuals.png)" >> .github/images/${{ env.report }}.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated README
          file_pattern: '.github/images/${{ env.report }}.md .github/images/feature_importance.png .github/images/residuals.png'
          branch: experiment1
